#!/bin/bash
#
# This will generate a random password. You can specify a length also using the options
# and whether or not to use special chars.

# With special chars
# tr -cd '[:punct:][:alnum:]' < /dev/urandom | fold -w30 | head -n1 |cut -b -20

# Without special chars
# tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 |cut -b -20

usage() {
echo ""
echo "Usage: $0 -S -z<size> "
echo "-S  Without special characters"
echo " <size> specify a size to use. Defaults to 20 characters"
echo ""
exit 1
}

size=20
spchar="yes"

while getopts "Sz:" opt; do
    case "$opt" in
        S) spchar="no"  
        ;;
        z) size=${OPTARG}
        ;;
        *) usage
        ;;
    esac
done

if [[ $spchar = "no" ]]; then
	tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 |cut -b -${size}
else
	tr -cd '[:punct:][:alnum:]' < /dev/urandom | fold -w30 | head -n1 |cut -b -${size}
fi



